name: migraphx

on: [push]


jobs:
  cancel:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

  build_docker:
    runs-on: ROCM-Ubuntu
    steps: 
    - uses: actions/checkout@v3

    - name: check image list
      run: docker image ls

    - name: check File System Size
      run: df -h

    # In this step, this action saves a list of existing images,
    # the cache is created without them in the post run.
    # It also restores the cache if it exists.
    - name: Docker layer cache
      uses: jpribyl/action-docker-layer-caching@v0.1.1
      with:
        key: docker-layer-caching-migraphx-${{hashFiles('**/hip-clang.docker')}}
        restore-keys:
          docker-layer-caching-migraphx
      # Ignore the failure of a step and avoid terminating the job.
      continue-on-error: true

    - name: check image list
      run: docker build . --file hip-clang.docker --tag migraphx

  run_test:
    runs-on: ubuntu-latest
    needs: build_docker
    steps:
    - uses: actions/checkout@v3

    # In this step, this action saves a list of existing images,
    # the cache is created without them in the post run.
    # It also restores the cache if it exists.
    - name: Docker layer cache
      uses: jpribyl/action-docker-layer-caching@v0.1.1
      with:
        key: docker-layer-caching-migraphx-${{hashFiles('**/hip-clang.docker')}}
        restore-keys:
          docker-layer-caching-migraphx
      # Ignore the failure of a step and avoid terminating the job.
      continue-on-error: false

    - name: check image list
      run: docker image ls

    - name: check File System Size
      run: df -h

    - name: Load Docker image
      shell: bash -c "docker run -i -v=$GITHUB_WORKSPACE:/data -w /data migraphx bash < {0}"
      run: |
        ls -l /opt 

