on: [push]

jobs:

  cancel:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

  build_docker:
    runs-on: ubuntu-latest
    name: Create a docker
    steps:
    - uses: actions/checkout@v3

    - name: Check file size
      run: |
        df -h

    - name: Build the Docker image
      run: |
        docker build . --file hip-clang.docker --tag migraphx:${GITHUB_REF##*/}

    - name: Check file size
      run: |
        df -h

    - name: Save the Docker image to gz
      run: |
        docker save migraphx:${GITHUB_REF##*/} | gzip > migraphx_${GITHUB_REF##*/}.tar.gz

    - name: Check file size
      run: |
        df -h

    - name: Cache the image
      uses: actions/upload-artifact@master
      with:
        name: my-artifact
        path: migraphx_${GITHUB_REF##*/}.tar.gz