name: migraphx

on: [push]

env:
  DOCKER_USER: ${{secrets.DOCKERHUB_USERID}}
  DOCKER_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}

jobs:
  cancel:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

  check_image:
    name: Check if image exists in registry
    runs-on: ubuntu-latest
    outputs:
      imageexists:  ${{ steps.check_image.outputs.imageexists }}
      imagetag:  ${{ steps.image_hash.outputs.imagetag }}

    steps: 
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Create Image Tag
        id: image_hash
        run: |
          echo "imagetag=rocm/migraphx-private:hip-clang-${{hashFiles('**/hip-clang.docker')}}" >> $GITHUB_OUTPUT

      - name: Check if image is built already
        id: check_image
        env:
          DOCKERIMAGE: ${{ steps.image_hash.outputs.imagetag }}
        run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin

          if [[ "$(docker manifest inspect $DOCKERIMAGE 2> /dev/null)" != "" ]]; then
            echo "imageexists=true" >> $GITHUB_OUTPUT
            echo "Image already exists, skip building available"
          else
            echo "imageexists=false" >> $GITHUB_OUTPUT
            echo "Tag does not exist, build and publishing required"
          fi

  build_image:
    name: Build image
    runs-on: ubuntu-latest
    needs: check_image
    if: ${{ needs.check_image.outputs.imageexists != 'true' }}
    steps:
    - uses: actions/checkout@v3

    # temporary workaround for an error in free disk space action
    # https://github.com/jlumbroso/free-disk-space/issues/14
    - name: Update Package List and Remove Dotnet
      run: |
        sudo apt-get update
        sudo apt-get remove -y '^aspnetcore-.*' --fix-missing || true
        sudo apt-get remove -y '^dotnet-.*' --fix-missing || true

    - name: Free space
      uses: jlumbroso/free-disk-space@main
      continue-on-error: true
      with:
        tool-cache: true
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        swap-storage: true
        docker-images: true
      

    - name: Build and publish 
      env:            
        DOCKERIMAGE: ${{ needs.check_image.outputs.imagetag }}
      run: |
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin
        docker build . --file hip-clang.docker --tag $DOCKERIMAGE;
        docker push $DOCKERIMAGE;


  run_test:
    runs-on: ubuntu-latest
    needs: build_image
    if: ${{ !cancelled() && (needs.build_image.result == 'success' || needs.build_image.result == 'skipped') }}
    steps:
    - uses: actions/checkout@v3

    ## temporary workaround for an error in free disk space action
    ## https://github.com/jlumbroso/free-disk-space/issues/14
    #- name: Update Package List and Remove Dotnet
    #  run: |
    #    sudo apt-get update
    #    sudo apt-get remove -y '^aspnetcore-.*' --fix-missing || true
    #    sudo apt-get remove -y '^dotnet-.*' --fix-missing || true 

    #- name: Free space
    #  uses: jlumbroso/free-disk-space@main
    #  continue-on-error: true      
    #  with:
    #    tool-cache: true
    #    android: true
    #    dotnet: true
    #    haskell: true
    #    large-packages: true
    #    swap-storage: true
    #    docker-images: true

    - name: Pull Docker
      run: |
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin

    - name: Run Docker
      env:
        DOCKERIMAGE: ${{ check_image.outputs.imagetag }}

      shell: bash -c "docker run -i -v=$GITHUB_WORKSPACE:/data -w /data $DOCKERIMAGE bash < {0}"
      run: |
        ls -l /opt 

