on: [push]

jobs:
  build_docker:
    runs-on: ubuntu-latest
    name: Create a docker
    steps:
    - uses: actions/checkout@v3

    - name: create cache
      uses: actions/cache@v3
      with:
        key: ${{hashFiles('**/hip-clang.docker')}}-cache
    
    - name: Docker layer cache
      uses: jpribyl/action-docker-layer-caching@v0.1.1
      with:
        key: docker-layer-caching-migraphx-${{hashFiles('**/hip-clang.docker')}}
        restore-keys:
          docker-layer-caching-migraphx-
      # Ignore the failure of a step and avoid terminating the job.
      continue-on-error: true

    - name: Build the Docker image
      run: |
        docker build . --file hip-clang.docker --tag migraphx
